language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
script:
- npm test
env:
  matrix:
  - CI=true
  - secure: U0enEAzj2ee0e30uWDL/IpEEO34pHLGYhxiAogyW2oZ+MmTh0aEN6eAG6SV0WZw+sUrwXe/+4LLM+kchl+beks/KtCOGWPcLnOlx1AszgWS+ZEyiYJKqH11+kpXjKqmhjYkTIa9L4oVH1+QlO6gMR4lj1gsCMJRLlVe9jOXHqvikCf2pZ/iQhpdcpSD+ZrdHJHV3TF82VT1OHu5tZFKhyb2vD0W34d6XcXccvcakj/IZYqPsuenseHE2BU8424Jj7bscGjAuBB5v/n2OmVUjYu6fJU2q1W9gT3EK+zaCHSFwgrNMa1EnzLZ1EOd34UgfWNghOw3K3F688oO8Qe2pQOQtyX4OQ3dS7rksiGbu/e34OeN9yvzA4EPWxi4vtkm1ESDF4cV7jFNBB087h7UYoL13f6Otc3vyVrnY8YpxguGzc7yRClgzvGGyAg+QUhKySn6zlzQ63R1405u4KDt4DlMxrJntQ7vvA49a1efMCbiS79AYLOor8vR9YpAO4WCAnSei+KUr7hErt+v19KQO6tiFIiB42Nu7kvEXChh2zYcIW60qYcEdtuLYmwCEMkFOZWjIFoKNZcFW4vbfGs3IFkrvHWY1HL+yLaFSJ9d9to7OQQ17UPzLXX2Zz/Gxu8lUxYbkHiYB1JtOk4t+3WTbDdDicIVJ3GeUsBgUYe+/1p4=
before_deploy:
- npm install netlify-cli -g
- npm run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
